#!/bin/bash
# Regenerate /etc/snmp/snmpd.conf.d/meridian-communities.conf from the
# current rows in the Meridian DB. Invoked:
#   · on install by install.sh
#   · by the portal when an admin saves a community (via a tight
#     sudoers wrapper — see /etc/sudoers.d/meridian-snmp)
#
# The file contains ONLY community-string declarations; other
# snmpd config (view, pass_persist, agentaddress) lives in the
# adjacent meridian.conf and never changes at runtime.
set -euo pipefail

OUT=/etc/snmp/snmpd.conf.d/meridian-communities.conf
TMP="${OUT}.tmp.$$"

{
  echo "# Regenerated by scripts/regenerate-snmpd.sh at $(date -u +%FT%TZ)"
  echo "# Do not edit by hand — changes are overwritten on the next portal save."
  echo
  sudo -u postgres psql -d meridian -tAc "
    SELECT
      CASE WHEN access='rw' THEN 'rwcommunity' ELSE 'rocommunity' END
      || ' ' || community
      || ' ' ||
      CASE
        WHEN cardinality(allowed_sources)=0 THEN 'default'
        ELSE array_to_string(allowed_sources, ',')
      END
    FROM snmp_communities WHERE enabled;
  "
} > "$TMP"

install -o root -g root -m 0600 "$TMP" "$OUT"
rm -f "$TMP"

# snmpd reloads its config on SIGHUP.
if systemctl is-active --quiet snmpd.service; then
  systemctl reload snmpd.service 2>/dev/null \
    || systemctl restart snmpd.service
fi
